### PR TITLE
Added unit tests for functions which are supposed to return default structs

### PR DESCRIPTION
**Pull request by sandlerben**

### CODE REVIEW

**Comment by sandlerben** [comment]
r @sectioneight

**Comment by sectioneight** [comment]
This seems fine, although I'm unclear on the value these tests provide. As you can see from the coveralls report, these paths were already tested, and it's a tautology that they return a non-nil value -- that is checked for us by the compiler.

I'm fine merging, but I don't think we actually gain anything by adding these tests.

**Comment by sandlerben** [comment]
I don't think all these paths are tested, see https://coveralls.io/builds/3150350/source?filename=graph%2Fgraph.go

**Comment by sectioneight** [comment]
Hmm fair enough, not sure why coveralls isn't picking up the change yet. This is the build for this PR: https://coveralls.io/builds/3150294/source?filename=graph%2Fgraph.go

**Pull request merged**
