### PR TITLE
Re-enable coveralls

### LINKED ISSUE #7: Fix coveralls integration
I tried to do this in #5, but coveralls kept returning blank data. We should fix this and get a shiny coverage badge.

### PR DESCRIPTION
**Pull request by sectioneight**
Fixes #7

### CODE REVIEW

**Comment by sandlerben** [comment]
lgtm

**Comment by sectioneight** [comment]
i have no idea why coveralls isn't showing any data. i will try this again tomorrow to see if it's just a transient failure.

**Comment by sectioneight** [comment]
Looks like coveralls is having a bad day: http://status.coveralls.io/

**Comment by sectioneight** [comment]
Their queue is growing which is why the results aren't showing. As I suspected earlier, this repo is set up fine. I've subscribed to their status updates and will bump this PR when coveralls is working again.

screen shot 2015-07-22 at 8 33 26 pm

**Comment by sandlerben** [comment]
@sectioneight What is the status of this?

**Comment by sectioneight** [comment]
coveralls outage is ongoing. following their status updates.

**Pull request merged**
