### PR TITLE
Add coveralls badge to readme header

### PR DESCRIPTION
**Pull request by sectioneight**
Hopefully this will inspire us to write some more tests. Currently at 87%, which is not bad :)

### CODE REVIEW

**Comment by sectioneight** [comment]
Preview here: https://github.com/uber/go-torch/blob/b9160724b0548a8ae4d60c12e682d63be72136b0/README.md

r @sandlerben

**Comment by sandlerben** [comment]
@sectioneight lgtm. It will be hard to increase coverage because

* Functions like [runPerlScript](https://github.com/uber/go-torch/blob/master/visualization/visualization.go#L85) are really hard to test. For example, in this case, I don't know how we could mock whether or not the flame graph script is installed.  
* We cannot test any code like `if err != nil {
		log.Fatal(err)
	}` because there is no way to recover from a Fatal.

**Comment by sectioneight** [comment]
@sandlerben I was just teasing, this project has excellent coverage. As you've pointed out, particularly compared to some of our dynamic-language codebases, you will almost always end up with fewer testable codepaths with Go. I don't think 87% is anything to be ashamed of; quite the contrary, it's very good for a project like this. I think this project should wear it proudly :)

**Comment by sandlerben** [comment]
Oh haha, that went over my head. I just want the badge to be green (not this ugly shade of yellow)!

**Pull request merged**
