### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by mikespook**
Fixed some tiny typos in Readme.

### CODE REVIEW

**Comment by sandlerben** [comment]
This isn't a typo: https://golang.org/pkg/net/http/pprof

**Comment by sandlerben** [comment]
Misread at first, I do think this is a typo

**Comment by prashantv** [comment]
Thanks for the contribution @mikespook 

Can you please sign the [Uber CLA](https://docs.google.com/a/uber.com/forms/d/e/1FAIpQLSfu-DmpJD5wYYUOxY50noHF9BWJwDbV0d2W1w45oEIbIx72RQ/viewform)? Thanks!

**Comment by mikespook** [comment]
No problem. I've already done with Uber CLA. Cheers

**Comment by prashantv** [comment]
Great, thanks!

**Pull request merged**
